version: '2'

services:
  couchdb:
    container_name: couchdb
    build: ./couchdb
    ports: 
      - "5984:5984"
    volumes:
      - couchdb_data:/data
    restart: unless-stopped

  scanner:
    container_name: scanner
    build: ./scanner
    depends_on:
      - couchdb
    privileged: true
    network_mode: host
    restart: unless-stopped

  api:
    container_name: api
    build: ./api
    depends_on:
      - couchdb
    restart: unless-stopped

  web:
    container_name: web
    build: ./ui
    depends_on:
      - api
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  couchdb_data: