version: '2'

services:
  couchdb:
    container_name: lls-couchdb
    build: ./couchdb
    ports: 
      - "59084:5984"
    volumes:
      - lls-data:/data
    restart: unless-stopped

  scanner:
    container_name: lls-scanner
    build: ./scanner
    depends_on:
      - couchdb
    privileged: true
    network_mode: host
    restart: unless-stopped

  api:
    container_name: lls-api
    build: ./api
    depends_on:
      - couchdb
    restart: unless-stopped

  web:
    container_name: lls-web
    build: ./ui
    depends_on:
      - api
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  lls-data: