apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-api
  labels:
    app: {{ .Chart.Name }}-api
spec:
  ports:
  - name: api
    port: {{ .Values.api.container.apiPort }}
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}-api