apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-couchdb
  labels:
    app: {{ .Chart.Name }}-couchdb

spec:
  
  replicas: {{ .Values.couchdb.replicaCount }}
  
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-couchdb
      app.kubernetes.io/instance: {{ .Release.Name }}
  
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-couchdb
        app.kubernetes.io/instance: {{ .Release.Name }}

    spec:
    {{- with .Values.couchdb.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}

      volumes:
        - name: {{ .Chart.Name }}{{ .Values.couchdb.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}{{ .Values.couchdb.volume.name }}-pvclaim

      containers:
        - name: {{ .Chart.Name }}-couchdb
          image: "{{ .Values.couchdb.image.repository }}:{{ .Values.couchdb.image.tag }}"
          imagePullPolicy: {{ .Values.couchdb.image.pullPolicy }}

          ports:
            - name: couchdb-port
              containerPort: {{ .Values.couchdb.container.couchdbPort }}
              protocol: {{ .Values.couchdb.container.couchdbProtocol }}

          volumeMounts:
            - name: {{ .Chart.Name }}{{ .Values.couchdb.volume.name }}
              mountPath: /data

      {{- if .Values.affinity.value }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: {{ .Values.affinity.weight }}
              preference:
                matchExpressions:
                  - key: "{{ .Values.affinity.label }}"
                    operator: In
                    values: 
                      {{- range .Values.affinity.value }}
                      - {{ . | quote }}
                      {{- end }}
      {{- end }}
