apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-couchdb
  labels:
    app: {{ .Chart.Name }}-couchdb
spec:
  ports:
  - name: couchdb
    port: {{ .Values.couchdb.container.couchdbPort }}
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}-couchdb