apiVersion: v1
kind: Secret
metadata:
  name: couchdb-network-storage-cifs-secret
type: fstab/cifs
data:
  username: '{{ required "couchdb.volme.serverUser required!" .Values.couchdb.volume.serverUser | b64enc }}'
  password: '{{ required "couchdb.volume.serverPassword required!" .Values.couchdb.volume.serverPassword | b64enc }}'