apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-ui
  labels:
    app: {{ .Chart.Name }}-ui

spec:
  
  replicas: {{ .Values.replicaCount }}
  
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-ui
      app.kubernetes.io/instance: {{ .Release.Name }}
  
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-ui
        app.kubernetes.io/instance: {{ .Release.Name }}

    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}

      volumes:
        - name: nginx-conf
          configMap: 
            name: local-location-services-ui-nginx-config
            items: 
              - key: nginx-conf
                path: default

      containers:
        - name: {{ .Chart.Name }}-ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/sites-available/
              readOnly: true

          ports:
            - name: http-tcp
              containerPort: {{ .Values.ui.container.port }}
              protocol: TCP

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
