apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}

spec:
  selector:
    app: {{ .Chart.Name }}-ui
  externalTrafficPolicy: Local
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: {{ required "externalIp required!" .Values.ui.container.externalIp }}

  ports:
  - name: http
    port: {{ .Values.ui.container.port }}
    protocol: TCP
    targetPort: http-tcp
  