# Default values for local-location-services.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

couchdb:
  image:
    repository: local-location-services-couchdb
    tag: latest
    pullPolicy: IfNotPresent

  volume:
    name: "-couchdb-data"
    server: 
    path: "/storage/local-location-services/couchdb"
    mountOptions: "vers=1.0"
    serverSecretName: "couchdb-network-storage-cifs-secret"

  container:
    couchdbPort: 5984
    couchdbProtocol: TCP

scanner:
  image:
    repository: local-location-services-scanner
    tag: latest
    pullPolicy: IfNotPresent
  container:
    couchdbHost: local-location-services-couchdb
    snmpHost: 
    snmpOid: "iso.3.6.1.2.1.3.1.1.2.0.1."

api:
  image:
    repository: local-location-services-api
    tag: latest
    pullPolicy: IfNotPresent
  container:
    couchdbHost: local-location-services-couchdb
    apiPort: 80

ui:
  image:
    repository: local-location-services-ui
    tag: latest
    pullPolicy: IfNotPresent
  container:
    externalIp:
    port: 80

  nginx:
    apiEndpoint: local-location-services-api


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""