# Default values for local-location-services.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

couchdb:
  image:
    repository: local-location-services-couchdb
    tag: latest
    pullPolicy: IfNotPresent

  volume:
    name: "-couchdb-data"
    server: 
    path: "/storage/local-location-services/couchdb"
    mountOptions: "vers=1.0,dir_mode=0755,file_mode=0644,noperm"

  container:
    couchdbPort: 5984
    couchdbProtocol: TCP

scanner:
  replicaCount: 1
  image:
    repository: local-location-services-scanner
    tag: latest
    pullPolicy: IfNotPresent
  container:
    couchdbHost: local-location-services-couchdb
    snmpHost: 
    snmpOid: "iso.3.6.1.2.1.3.1.1.2.0.1."

api:
  replicaCount: 1
  image:
    repository: local-location-services-api
    tag: latest
    pullPolicy: IfNotPresent
  container:
    couchdbHost: local-location-services-couchdb
    apiPort: 80

ui:
  replicaCount: 1
  image:
    repository: local-location-services-ui
    tag: latest
    pullPolicy: IfNotPresent
  container:
    externalIp:
    port: 80

  nginx:
    apiEndpoint: local-location-services-api

affinity:
  weight: 100
  label: 
  value:

secrets:
  dataVolumeServerSecretName: "local-location-services-couchdb-network-storage-cifs-secret"


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""